### ISSUE TITLE
[错误报告]: “清理QB无效做种”插件中，“err torrent not registered with this tracker”不会被视为失效做种

### ISSUE THREAD

**Issue by moriecho** [jxxghp/MoviePilot#3566]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.0.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

插件版本：V2.0
已确定站内删种了，插件已经检测到“err torrent not registered with this tracker ”的tracker状态，但未被认定为“无效做种”，不能触发自动删种或自动标记

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-12-19 18:40:24,165 - cleaninvalidseed - 未配置下载目录，无法检测未做种无效源文件
【INFO】2024-12-19 18:40:24,108 - cleaninvalidseed - 开始检测未做种的无效源文件
【INFO】2024-12-19 18:40:24,106 - cleaninvalidseed - 检测无效做种任务结束

3. The.Wild.Robot.2024.2160p.AMZN.WEB-DL.DDP5.1.Atmos.H.265-Breeze@Sunny，分类：保种，标签：Sunny, 原种, 大小：11.25G，Trackers:  tracker.sunnypt.top：err torrent not registered with this tracker 
2. The.Wild.Robot.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-Breeze@Sunny，分类：保种，标签：Sunny, 原种, 大小：17.74G，Trackers:  tracker.sunnypt.top：err torrent not registered with this tracker 
1. The.Wild.Robot.2024.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-Breeze@Sunny，分类：保种，标签：Sunny, 原种, 大小：6.11G，Trackers:  tracker.sunnypt.top：err torrent not registered with this tracker 
【INFO】2024-12-19 18:40:22,347 - cleaninvalidseed - 检测到3个tracker未工作做种，请检查种子状态

【INFO】2024-12-19 18:40:22,346 - cleaninvalidseed - 检测到0个失效做种
【INFO】2024-12-19 18:40:22,339 - cleaninvalidseed - 初筛共有0个无效做种
【INFO】2024-12-19 18:40:21,923 - cleaninvalidseed - 开始清理 PT保种 无效做种...
【INFO】2024-12-19 18:40:18,921 - cleaninvalidseed - 清理无效种子服务启动，立即运行一次
```
